from tkbuilder.widgets.widget_wrappers.button import Button
from tkbuilder.widgets.widget_wrappers.canvas import Canvas
from tkbuilder.widgets.widget_wrappers.combobox import Combobox
from tkbuilder.widgets.widget_wrappers.scale import Scale
from tkbuilder.widgets.widget_wrappers.label import Label
from tkbuilder.widgets.widget_wrappers.labelFrame import LabelFrame
from tkbuilder.widgets.widget_wrappers.entry import Entry
from tkbuilder.widgets.widget_wrappers.text import Text
from tkbuilder.widgets.widget_wrappers.spinbox import Spinbox
from tkbuilder.widgets.widget_wrappers.radiobutton import RadioButton
from tkbuilder.widgets.widget_wrappers.checkbutton import CheckButton